### ISSUE TITLE
No waiting status update after sending transaction

### ISSUE THREAD

**Issue by lochjin** [eth-infinitism/bundler#174]
yarn run v1.22.18
$ lerna run hardhat-deploy --stream --no-prefix -- --network localhost --show-stack-traces
lerna notice cli v5.6.2
lerna info Executing command in 1 package: "yarn run hardhat-deploy --network localhost --show-stack-traces"
$ hardhat deploy --network localhost --show-stack-traces
Nothing to compile
No need to generate any newer typings.
An unexpected error occurred:
Error: ERROR processing /bundler/packages/bundler/deploy/2-deploy-entrypoint.ts:
Error: raw TX didn't deploy deployer!
    at DeterministicDeployer.deployFactory (/bundler/packages/sdk/dist/src/DeterministicDeployer.js:44:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DeterministicDeployer.getDeployTransaction (/bundler/packages/sdk/dist/src/DeterministicDeployer.js:48:9)
    at async DeterministicDeployer.deterministicDeploy (/bundler/packages/sdk/dist/src/DeterministicDeployer.js:88:42)
    at async Object.deployEP [as func] (/bundler/packages/bundler/deploy/2-deploy-entrypoint.ts:22:3)
    at async DeploymentsManager.executeDeployScripts (/bundler/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1226:22)
    at async DeploymentsManager.runDeploy (/bundler/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1059:5)
    at async SimpleTaskDefinition.action (/bundler/node_modules/hardhat-deploy/src/index.ts:438:5)
    at async Environment._runTaskDefinition (/bundler/node_modules/hardhat/src/internal/core/runtime-environment.ts:333:14)
    at async Environment.run (/bundler/node_modules/hardhat/src/internal/core/runtime-environment.ts:166:14)
    at DeploymentsManager.executeDeployScripts (/bundler/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1229:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DeploymentsManager.runDeploy (/bundler/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1059:5)
    at async SimpleTaskDefinition.action (/bundler/node_modules/hardhat-deploy/src/index.ts:438:5)
    at async Environment._runTaskDefinition (/bundler/node_modules/hardhat/src/internal/core/runtime-environment.ts:333:14)
    at async Environment.run (/bundler/node_modules/hardhat/src/internal/core/runtime-environment.ts:166:14)
    at async SimpleTaskDefinition.action (/bundler/node_modules/hardhat-deploy/src/index.ts:584:32)
    at async Environment._runTaskDefinition (/bundler/node_modules/hardhat/src/internal/core/runtime-environment.ts:333:14)
    at async Environment.run (/bundler/node_modules/hardhat/src/internal/core/runtime-environment.ts:166:14)
    at async SimpleTaskDefinition.action (/bundler/node_modules/hardhat-deploy/src/index.ts:669:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run hardhat-deploy --network localhost --show-stack-traces exited 1 in '@account-abstraction/bundler'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by drortirosh** [comment]
what network did you try to deploy to? I can see an error `raw TX didn't deploy deployer`.
Probably this network doesn't support pre-EIP155 transaction.
for geth, it requires setting `--rpc.allow-unprotected-txs`
